### ISSUE TITLE
DSMR-Reader not starting after last update (2021.12.1 and 2021.12.2)

### ISSUE THREAD

**Issue by canedje** [xirixiz/dsmr-reader-docker#230] opened 2021-12-16 16:32 UTC
### Issue

After last update docker will not connect/start anymore

Log is giving permission error

Running DSMR-Reader as docker under unraid

### Which version has the issue?

2021.12.1 and 2021.12.2

### What was the last working version?

2021.10.2

### What type of installation are you running (architecture)?

AMD64

### Anything in the logs that might be useful?

```txt
Operations to perform:
Apply all migrations: admin, auth, contenttypes, dsmr_api, dsmr_backend, dsmr_backup, dsmr_consumption, dsmr_datalogger, dsmr_dropbox, dsmr_frontend, dsmr_influxdb, dsmr_mindergas, dsmr_mqtt, dsmr_notification, dsmr_pvoutput, dsmr_stats, dsmr_weather, sessions
Running migrations:
No migrations to apply.

563 static files copied to '/var/www/dsmrreader/static'.
Updating password of superuser "canedje"
Deactivating any other existing superusers
Traceback (most recent call last):
File "/usr/bin/supervisord", line 33, in <module>
sys.exit(load_entry_point('supervisor==4.2.1', 'console_scripts', 'supervisord')())
File "/usr/lib/python3.8/site-packages/supervisor/supervisord.py", line 361, in main
go(options)
File "/usr/lib/python3.8/site-packages/supervisor/supervisord.py", line 371, in go
d.main()
File "/usr/lib/python3.8/site-packages/supervisor/supervisord.py", line 72, in main
self.options.make_logger()
File "/usr/lib/python3.8/site-packages/supervisor/options.py", line 1470, in make_logger
loggers.handle_file(
File "/usr/lib/python3.8/site-packages/supervisor/loggers.py", line 415, in handle_file
handler = FileHandler(filename)
File "/usr/lib/python3.8/site-packages/supervisor/loggers.py", line 160, in __init__
self.stream = open(filename, mode)
PermissionError: [Errno 13] Permission denied: '/dev/stdout'
Operations to perform:
Apply all migrations: admin, auth, contenttypes, dsmr_api, dsmr_backend, dsmr_backup, dsmr_consumption, dsmr_datalogger, dsmr_dropbox, dsmr_frontend, dsmr_influxdb, dsmr_mindergas, dsmr_mqtt, dsmr_notification, dsmr_pvoutput, dsmr_stats, dsmr_weather, sessions
Running migrations:
No migrations to apply.

0 static files copied to '/var/www/dsmrreader/static', 563 unmodified.
Updating password of superuser "canedje"
Deactivating any other existing superusers
Traceback (most recent call last):
File "/usr/bin/supervisord", line 33, in <module>
sys.exit(load_entry_point('supervisor==4.2.1', 'console_scripts', 'supervisord')())
File "/usr/lib/python3.8/site-packages/supervisor/supervisord.py", line 361, in main
go(options)
File "/usr/lib/python3.8/site-packages/supervisor/supervisord.py", line 371, in go
d.main()
File "/usr/lib/python3.8/site-packages/supervisor/supervisord.py", line 72, in main
self.options.make_logger()
File "/usr/lib/python3.8/site-packages/supervisor/options.py", line 1470, in make_logger
loggers.handle_file(
File "/usr/lib/python3.8/site-packages/supervisor/loggers.py", line 415, in handle_file
handler = FileHandler(filename)
File "/usr/lib/python3.8/site-packages/supervisor/loggers.py", line 160, in __init__
self.stream = open(filename, mode)
PermissionError: [Errno 13] Permission denied: '/dev/stdout'
```

### Additional information

Rolling back is running again

docker:
![image](https://user-images.githubusercontent.com/23150947/146410928-19467674-9c64-44e3-a279-8c43919319e7.png)

**Comment by sanderdw** [comment] 2021-12-16 16:38
Indeed, same error here.

**Comment by canedje** [comment] 2021-12-16 16:42
Rolling back is running but Log shows also error:
"http://192.168.2.230:8888/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36" "-"
192.168.2.28 - - [16/Dec/2021:17:39:58 +0100] "GET /static/dsmr_frontend/js/dsmr-reader/consumption-header.js?r=v4.19 HTTP/1.1" 304 0 "http://192.168.2.230:8888/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36" "-"
192.168.2.28 - - [16/Dec/2021:17:39:58 +0100] "GET /static/dsmr_frontend/fonts/downloads/1YwB1sO8YE1Lyjf12WNiUA.woff2 HTTP/1.1" 304 0 "http://192.168.2.230:8888/static/dsmr_frontend/css/lato-font.css?r=v4.19" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36" "-"
192.168.2.28 - - [16/Dec/2021:17:39:58 +0100] "GET /static/dsmr_frontend/fontawesome-free-5.15.4-web/webfonts/fa-solid-900.woff2 HTTP/1.1" 304 0 "http://192.168.2.230:8888/static/dsmr_frontend/fontawesome-free-5.15.4-web/css/all.min.css?r=v4.19" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36" "-"
192.168.2.28 - - [16/Dec/2021:17:39:58 +0100] "GET /xhr/header HTTP/1.1" 200 148 "http://192.168.2.230:8888/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36" "-"
192.168.2.28 - - [16/Dec/2021:17:39:58 +0100] "GET /static/dsmr_frontend/img/favicons/favicon.png HTTP/1.1" 304 0 "http://192.168.2.230:8888/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36" "-"
192.168.2.28 - - [16/Dec/2021:17:39:59 +0100] "GET /xhr/header HTTP/1.1" 200 148 "http://192.168.2.230:8888/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36" "-"
2021-12-16 17:40:14,507 ERROR schedule execute_scheduled_processes 37 | (PermissionError) dsmr_backup.services.backup.run errored: [Errno 13] Permission denied: '/dsmr/\\backups'

2021-12-16 17:40:44,694 ERROR schedule execute_scheduled_processes 37 | (PermissionError) dsmr_backup.services.backup.run errored: [Errno 13] Permission denied: '/dsmr/\\backups'

2021-12-16 17:41:14,992 ERROR schedule execute_scheduled_processes 37 | (PermissionError) dsmr_backup.services.backup.run errored: [Errno 13] Permission denied: '/dsmr/\\backups'

2021-12-16 17:41:45,185 ERROR schedule execute_scheduled_processes 37 | (PermissionError) dsmr_backup.services.backup.run errored: [Errno 13] Permission denied: '/dsmr/\\backups'

**Comment by xirixiz** [comment] 2021-12-16 21:20
Hi, will have a look. Most probably you're not running DSMR as the default user (root).
Should be easy to fix.

**Comment by xirixiz** [comment] 2021-12-16 21:33
PR merged and pipeline is building/running

Changes: https://github.com/xirixiz/dsmr-reader-docker/pull/231/files

Made some changes during testing and didn't put those back. Release 2021.12.03 will be available in about 20 minutes.

**Comment by canedje** [comment] 2021-12-17 05:50
sorry to tell. But the same error. No changes after update to 2021.12.3

**Comment by xirixiz** [comment] 2021-12-17 07:16
My guess is that the security settings on your mount are corrupt.
Can you fix the persmissions/access?

- /mnt/users/appdata/dsmr-reader/backups is the source on your unraid.

The problem is that Docker doesn't have access to the mounted folder from unraid in the Docker container, this might be the result of the previous Docker image, therefore rolling back to an older image also doesn't work. Should be easy to fix.

**Comment by canedje** [comment] 2021-12-17 12:07
Bram,

thanks for the answer.
The security settings are updated. 
but still the same error. 
This already from beginning I’m using dsmr the problem
in the dsmr app it’s talking about dsmr\backup
But I using dsmr-reader\backups
I tried all possibilities but always giving this error.

rolling back is working for the docker to run again.
But the backup error is always there

or I do something wrong with permissions?
There is a tool in unraid you can change permissions

**Comment by xirixiz** [comment] 2021-12-17 12:25
Aaah, oke, like that. Let me check into that later this weekend... I`ll get back to you.

**Comment by canedje** [comment] 2021-12-17 22:11
this repository:  xirixiz/dsmr-reader-docker:amd64-development is working.

The backup still  not.
The backup always adding /dsmr in front of the backup name
![image](https://user-images.githubusercontent.com/23150947/146613764-8ed98394-dd22-49b7-8df2-ea325c3e9bea.png)


Just for info

**Comment by xirixiz** [comment] 2021-12-18 07:19
I notice your backup path is incorrect. In your docker-compose I see the following line:

```
-v '/mnt/users/appdata/dsmr-reader/backups':'/home/dsmr/app/backups'
```
Which means that your local path ```/mnt/users/appdata/dsmr-reader/backups``` is mounted in the container as ```/home/dsmr/app/backups```. The backup path relative to the default DSMR path is best to use.

The best option imho would be:
Change the volume to ```-v '/mnt/users/appdata/dsmr-reader/backups':'/dsmr/backups' ```, and change the path in your DSMR config to:
![image](https://user-images.githubusercontent.com/11210639/146632940-a8b23929-47f5-4771-8417-b1a7b1435a12.png)

**Comment by canedje** [comment] 2021-12-18 08:31
Bart Thanks again.

I checked my docker settings.
It shows:
![image](https://user-images.githubusercontent.com/23150947/146634803-7968d6e1-5cde-4aa1-8f8e-48d39cb145e0.png)

So I quess I do need to change: /home/dsmr/app/backups to /dsmr/backup

I tried allready it worked!!
I am a dump in Dopckers. Thansk for the help.

The latest repository: xirixiz/dsmr-reader-docker:amd64-development is the right one?

**Comment by xirixiz** [comment] 2021-12-18 08:37
Great! ...and the name is Bram btw ;).

It was indeed the container path that needed some adjustments. The app (DSMR) is isolated to it's own folder.
But good to see it's resolved. Keep trying and exploring and you'll learn every time a bit more!

You should be able to use this image now. Another user with issues also confirmed it's working properly now. I believe the development image and current latest image are the same, so you should be safe to move back to the latest one again.
```
xirixiz/dsmr-reader-docker:latest
```

**Closed by xirixiz** 2021-12-18 08:37 UTC
Labels: bug, help wanted

**Comment by canedje** [comment] 2021-12-18 09:06
I know your Bram I don't know why I called yoy Bart.... :-)
Appologize.

But thanks again for the help

I will try lates now

**Comment by canedje** [comment] 2021-12-18 09:17
Maybe the docker image is not updated yet?
